### ISSUE TITLE
Research on Django rest framework

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#109]
## Issue Description
Make research on Django and Django rest framework. Find feasible libraries to use in project. 

## Tasks

- [x] Research Django and similar libraries for our project
- [x] Research Django and similar libraries for our project
- [x] Research what functions we will be use
- [x] Find YouTube videos to watch before coding, determine which are them essential 

## Estimated Time

**Estimated Time:** 6 hours

## Deadline

**Deadline:** 30/04/2024

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:**  30/04/2024
