### ISSUE TITLE
Start the backend repo and code the skeleton

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#110]
## Issue Description

Starting a repo for our backend and code the setup part of our code.
## Tasks

- [x] Start our backend repo
- [x] Pull backend repo
- [x] Setup with Django rest framework

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:**  30/04/2024

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:**  30/04/2024

**Comment by kaanyolcu22** [comment]
thanks @oktayozel @skywllker
