### ISSUE TITLE
Login and Signup views

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#111]
## Issue Description

Code login and signup views of our backend

## Tasks

- [x] Code Login view 
- [x] Code Signup view
- [x] Generate serializer and model for our user informations 

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:**  30/04/2024

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:**  30/04/2024

**Comment by kaanyolcu22** [comment]
Thanks, Halil It looks nice.
