### ISSUE TITLE
Configuring  and Dockerizing Database

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#113]
## Issue Description
Researching and Writing Dockerfile and docker_compose.yml for configuring mysql database.

## Tasks
- [x] ~Research Docker~ (Completed)
- [x] ~Writing Dockerfile~ (Completed)
- [x] ~Writing docker_compose.yml~ (Completed)
- [x] ~Configuring database to docker~ (Completed)

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 30/04/2024- 22:00

**Comment by yunusemreozdemir** [comment]
All tasks are completed, related commits can be found in this [pr](https://github.com/bounswe/bounswe2024group6/pull/90). Further fixes can be found in this [pr](https://github.com/bounswe/bounswe2024group6/pull/91). Can you check @arastasci ?
