### ISSUE TITLE
Milestone Report 2 - Fill Work Done by Each Member

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#147]
## Issue Description
Everyone must fill their work done by each member part on the report. Mark your task as completed when you fill it.
## Tasks

- [x] Anıl Köse
- [x] Aras Taşçı
- [x] Battal Hazar
- [x] Oktay Özel
- [x] Eymen Esad Çeliktürk 
- [x] Elif Nur Deniz
- [x] Yunus Emre Özdemir
- [x] Kaan Yolcu
- [x] Halil Özkan

## Deadline

**Deadline:** 03/05/2024 20.00

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:**03/05/2024 21.00
