### ISSUE TITLE
backend: write the views for building, style and architect wiki pages.

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#154]
## Issue Description

The frontend team provided the mock data for the building, style and architect wiki pages. We need to write the views for the pages.

## Task List

- [x] Implement Building Wiki Page Endpoint
- [x] Implement Architect Wiki Page Endpoint
- [x] Implement Style Wiki Page Endpoint
- [x] Merge the branch and migrate it to the current architecture

## Estimated Time

**Estimated Time:** 4.5 hours

## Deadline

**Deadline:** 16/05/2024 22:00

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:** 17/05/2024 12:00

**Comment by arastasci** [comment]
you can check PR #165 @kaanyolcu22

**Comment by kaanyolcu22** [comment]
thanks @arastasci
