### ISSUE TITLE
Implementing user profile view

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#204]
## Issue Description

Implement user profile to show user informations and posts he/she sent, liked, commented and bookmarked.
## Tasks

- [x] show bookmarked posts 
- [x] show liked posts
- [x] show commented posts
- [x] show sent posts
- [x] show user informations like bio, avatar

## Reviewer Assignment

**Reviewer:** @kaanyolcu22

**Comment by kaanyolcu22** [comment]
thanks @oktayozel @skywllker @yunusemreozdemir
