### ISSUE TITLE
Create a new backend base

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#205]
## Issue Description

Create a new backend file since our previous version is false in terms of structuring and hinders further improvements. Configure the files and database get it to a working condition

## Tasks

- [x] Start Django Project
- [x] Migrate previous works to that file 
- [x] connect to database and get it working
## Estimated Time

**Estimated Time:** 1 hours

## Deadline

**Deadline:** 16/05/2024 - 22:00

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:** 17/05/2024 - 09:00

**Comment by oktayozel** [comment]
@Elifnurdeniz can you check and close
https://github.com/bounswe/bounswe2024group6/commit/e2570978700d9ea434a72e4d8aba32214e46cf43

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
