### ISSUE TITLE
Add get post by ids andUpdate serializers and urls accordingly

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#214]
## Issue Description

add get post by ids it should return the post when frontend calls with an id in the body
update serializers accordingly to implement get posts by id
update urls.py

## Tasks

- [ ] add get post by ids it should return the post when frontend calls with an id in the body
- [ ] update serializers accordingly to implement get posts by id
- [ ] update urls.py
- [ ] 
## Estimated Time

*Estimated Time:* 1 hours

## Deadline

*Deadline:* 16/05/2024 - 22:00

## Reviewer Assignment

*Reviewer:* @kaanyolcu22 
*Review Deadline:* 17/05/2024 - 09:00

**Review Deadline:** DD/MM/YYYY - HH:MM

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
