### ISSUE TITLE
Update post retrieval function

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#215]
## Issue Description

update post retrieval function to return only a single function and handle the wrong id case and update the url path

## Tasks

- [ ] update post retrieval function to return only a single function
- [ ] handle the wrong id case
- [ ] update the url path

## Estimated Time

*Estimated Time:* 1 hours

## Deadline

*Deadline:* 16/05/2024 - 22:00

## Reviewer Assignment

*Reviewer:* @kaanyolcu22 
*Review Deadline:* 17/05/2024 - 09:00

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
