### ISSUE TITLE
Add "name" column to necessary field upon the request of frontend

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#216]
## Issue Description

updated user serializer and model for adding name columns. update the functions using name
## Tasks

- [ ] update user model
- [ ] update user serializer
- [ ] check other functions and update necessary fields

## Estimated Time

*Estimated Time:* 1 hours

## Deadline

*Deadline:* 16/05/2024 - 22:00

## Reviewer Assignment

*Reviewer:* @kaanyolcu22 
*Review Deadline:* 17/05/2024 - 09:00

**Comment by kaanyolcu22** [comment]
thanks @oktayozel
