### ISSUE TITLE
Writing Project report for backend development

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#223]
## Issue Description

Writing the backend part of the project documentation 
## Tasks

- [x] Write backend development
- [x] write challenges that you encountered
- [x] provide example code
- [x] write key features

## Reviewer Assignment

**Reviewer:** @kaanyolcu22
