### ISSUE TITLE
Writing project report for frontend part

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#224]
## Tasks

- [x] Writing technologies that we used
- [x] Writing challenges of the frontend development
- [x] Writing what we have done in frontend
- [x] Provide sample code of frontend part

## Reviewer Assignment

**Reviewer:** @kaanyolcu22
