### ISSUE TITLE
Write project report for mobile development

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2024group6#225]
## Tasks

- [x] Writing key features of what we have done
- [x] Writing challenges we encountered
- [x] Provide code sample of mobile
## Reviewer Assignment

**Reviewer:** @kaanyolcu22
