### ISSUE TITLE
Backend: Speed up Searching Functionality

### ISSUE THREAD

**Issue by arastasci** [bounswe/bounswe2024group6#247]
## Issue Description

Searching takes too long as a comprehensive query is made everytime a user makes a search. We saw that making a fast enough query is not possible, so we should resort to a different technique: pulling all data related to entities and storing them in our database to make a much faster query to our database.
## Tasks

- [x] Make a Django Model for the search results
- [x] Write a Python script that gathers all information with a Wikidata SPARQL query and stores it in the database
- [x] Embed that in our application in a way that this script is triggered at the start of a migration  (or when prompted)

## Estimated Time

**Estimated Time:** 5 hours

**Comment by arastasci** [comment]
can you take a look @kaanyolcu22 ?

**Comment by kaanyolcu22** [comment]
thanks @arastasci
