### ISSUE TITLE
Fix CORS errors, Set up MySQL connection, New Backend Dockerfile

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#248]
## Issue Description
Since we have migrated to the new backend, we need to fix CORS errors, set up MySQL connection and create the new Dockerfile for backend.

## Tasks

- [x] Fix CORS errors
- [x] Set up MySQL connection
- [x] Create backend Dockerfile and requirements.txt

## Reviewer Assignment
**Reviewer:** @Elifnurdeniz
