### ISSUE TITLE
Implement Dynamic Routing for Wiki Pages and Connection with Browser

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#250]
## Issue Description
We implemented the Browser page in the last milestone, now we need to link them to their respective Wiki pages with entity ids and dynamic routing.

## Tasks
- [x] Research on dynamic routing.
- [x] Implement dynamic routing on wiki pages.
- [x] Connect Browser page with Wiki pages with navigation and entity ids.

## Reviewer Assignment
**Reviewer:** @Elifnurdeniz
