### ISSUE TITLE
Implement Profile Page: UI, Dynamic Routing, Display/Edit Profile, Follow/Unfollow

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#252]
## Issue Description
We need to create a profile page to display user information and provide edit profile/follow/unfollow functionalities. 

## Tasks
- [x] Create new useAuth hook actions for profile display.
- [x] Create profile page ui
- [x] Add dynamic routing
- [x] Connect UI with user profile APIs
- [x] Implement Edit Profile Modal
- [x] Implement Edit Profile functionality
- [x] Implement Follow/Unfollow functionalities

## Reviewer Assignment
**Reviewer:** @Elifnurdeniz
