### ISSUE TITLE
Research W3C Standards & Choose the most suitable one for our team/project

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#270]
## Issue Description
It is compulsory for our project to utilize a W3C standard, and the few that were mentioned in the project descriptions are the **Web Annotation Data Model**, **Activity Streams 2.0** and **Web Content Accessibility Guidelines (WCAG) 2.2**. I don't think we are forced to use one of these three, but they are nonetheless a good place to start looking. We need to gather information about available standards and put it in a wiki page for easy access by all team members.

We then need to discuss among ourselves and put the standards in an ordering depending on how much we wish to work with them. Of course, we still need the TA's and the instructor's approval of our chosen standard, so we'll also have to have a chat with them after choosing the standards we like best. Finally, the home page of the wiki should be updated to reflect our decision.

## Tasks

- [x] Create a wiki article under 451 Research about various W3C standards, listing their benefits and drawbacks
- [x] Organize a meeting with the team members once the research is completed to reach an agreement regarding which standard to use
- [x] Reach out to the TA/Professor to get their approval of the chosen standard (this can be completed during lab hours)

## Estimated Time

**Estimated Time:** 3-4 hours

## Deadline

**Deadline:** 01/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @skywllker 
**Review Deadline:** 02/10/2024 - 23:59

**Comment by alitariksahin** [comment]
So we chose Activity Streams 2.0 among all. Here is the reasoning and our research results: [Research W3C Standards](https://github.com/bounswe/bounswe2024group6/wiki/W3C-Standards)

**Comment by alitariksahin** [comment]
@skywllker can you review this one

**Comment by skywllker** [comment]
good job
