### ISSUE TITLE
Preparation: Elicitation Process

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#272]
## Issue Description
Since we have decided to work on the requirements file in advance, we'll also need to have prepared in advance for the elicitation process. Once our preliminary requirements are decided on, we will be discussing our ideas with the TA (hopefully in the next lab if everything goes according to schedule). To help avoid confusion and dissatisfaction further down the line, we want to have gone over the requirements at least once to determine key places where they might be misunderstandings. It'd also be great to identify different possible options/ideas we have for the project and present the TA with them.

## Tasks

- [x] Go over the preliminary requirements file (once it's ready) and determine the areas that contain ambiguity/need further clarification
- [x] Brew different ideas/options for various parts of the requirements to show as an alternative to the TA. 
- [ ] (Optional) Gather ideas from other team members for alternative ideas.

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 01/10/2024 - 13:00

## Reviewer Assignment

**Reviewer:** @YavizGuldalf 
**Review Deadline:** 01/10/2024 - 15:00

**Comment by anilanlar** [comment]
Created a new elicitation questions page [here](https://github.com/bounswe/bounswe2024group6/wiki/Elicitation-Questions-CMPE-451), and added questions that I thought needed clarification. @YavizGuldalf could you check if the questions are OK?

**Comment by YavizGuldalf** [comment]
The questions look good, good work.
