### ISSUE TITLE
Wiki Update: Home Page 

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#275]
## Issue Description
Our current home page in the wiki is outdated, it should be updated to reflect the changes from last semester's class. We have new team members, and team members who have left. We also have to add the links to the meetings and update research.

## Tasks

- [x] Update members list in the home page.
- [x] Update meetings in the home page.
- [x] Update research in the home page.

## Estimated Time

**Estimated Time:** 1 hours

## Deadline

**Deadline:** 01/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @skywllker 
**Review Deadline:** 02/10/2024 - 23:59

**Comment by YavizGuldalf** [comment]
@skywllker I am done, can you check the new home page and comment if anything needs to get changed?

**Comment by skywllker** [comment]
reviewed it, great job
