### ISSUE TITLE
[Issue Title]: Setup Backend Infrastructure

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#284]
## Tasks

- [x] Setup Docker
- [x] Setup Backend Branch
- [x] Setup Database Connection
- [x] Setup Django App

## Estimated Time

**Estimated Time:** 5 hours

## Deadline

**Deadline:** 15 October

## Reviewer Assignment

**Reviewer:** @kaanyolcu22 
**Review Deadline:** 15 October

**Comment by oktayozel** [comment]
https://github.com/bounswe/bounswe2024group6/pull/301

@kaanyolcu22  can you close this issue.

**Comment by kaanyolcu22** [comment]
thanks , Oktay.
