### ISSUE TITLE
[Mockups]: Create Scenario Mockups

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#288]
## Issue Description
We need to create detailed use case scenarios to ensure all user interactions with the system are clearly defined and well-documented. These scenarios will serve as an example guide for development, testing, and future enhancements.

## Tasks
- [x] Create User Scenario 1 
- [x] Create User Scenario 2
- [x] Create User Scenario 3
- [x] Create User Scenario 4
- [x] Create User Scenario 5

## Estimated Time
**Estimated Time:** 3 hours

## Deadline
**Deadline:** 8/10/2024 - 19:30

## Reviewer Assignment
**Reviewer:** @oktayozel 
**Review Deadline:** 8/10/2024 - 20:00

**Comment by aoengin** [comment]
Scenario mockups have been created. 
[User Scenario 1](https://github.com/bounswe/bounswe2024group6/wiki/User-Scenario-1)
[User Scenario 2](https://github.com/bounswe/bounswe2024group6/wiki/User-Scenario-2)
[User Scenario 3](https://github.com/bounswe/bounswe2024group6/wiki/User-Scenario-3)
[User Scenario 4](https://github.com/bounswe/bounswe2024group6/wiki/User-Scenario-4)
[User Scenario 5](https://github.com/bounswe/bounswe2024group6/wiki/User-Scenario-5)

**Comment by oktayozel** [comment]
Thank you @aoengin
