### ISSUE TITLE
Setup Frontend Application

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#294]
## Issue Description
Fronted application should be initialized with the listed configurations and installations to facilitate further development.

## Tasks
- [x] Create React-TS Vite App
- [x] TypeScript configuration
- [x] Ant Design Setup
- [x] Tailwind CSS Setup
- [x] React Router Setup
- [x] Linter and formatter Setup

## Estimated Time
**Estimated Time:** 4 hours

## Deadline
**Deadline:** 16/10/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 19/10/2024 - 23:59
