### ISSUE TITLE
Checking Mock-ups, Diagrams and Requirements for Inconsistencies

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#297]
## Issue Description
Since these documents are critical to our project and were created separately by different groups of people, we need to make sure that there are no inconsistencies between them. Every requirement should be met in the mock-ups and diagrams.

## Tasks

- [x] Compare mobile and front-end mock-ups
- [x] Compare requirements and use-case diagram
- [x] Compare requirements and sequence diagrams
- [x] Compare requirements and mock-ups
- [x] Compare sequence diagrams and class diagrams

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 16/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @aoengin 
**Review Deadline:** 17/10/2024 - 23:59

**Comment by YavizGuldalf** [comment]
I have looked through the mock-ups, requirements, the use-case diagram and the sequence diagram, everything looks fine to me, except a few items in the requirements (which I changed in the wiki article in this [revision](https://github.com/bounswe/bounswe2024group6/wiki/Requirements-%E2%80%90-451/e819de449648d573d642c7fe4cc60bb8d7b1e5bd) (e819de4). I couldn't find the class diagrams on the wiki, but I asked the backend team to upload them if they are finished.

**Comment by Elifnurdeniz** [comment]
We stopped using the word "thread" in the forum domain. Instead we mention them as "post" and "comments". Maybe we can update the [Use Case Diagrams](https://github.com/bounswe/bounswe2024group6/wiki/Use-case-diagram-%E2%80%90-451#2-forum-app-subsystem) according to it.

**Comment by Elifnurdeniz** [comment]
According to the requirements and the sequence diagrams, users can login by entering their username and password. But according to the mockups, they should provide email instead. We should decide on one of them and update the related parts.

**Comment by Elifnurdeniz** [comment]
In the [requirements](https://github.com/bounswe/bounswe2024group6/wiki/Requirements-%E2%80%90-451) glossary, Quiz Difficulty Tag examples should be changed. We later decided to use #A2, #C1 etc. instead of #easy, #medium, #hard.

**Comment by aoengin** [comment]
All diagrams are checked.
