### ISSUE TITLE
1st Customer Presentation: Front-end Presentation

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#299]
## Issue Description
We decided that the front-end team will focus on showcasing the forums in the 1st customer presentation. In order to do this, the required pages have to be implemented and connected to the backend which will be serving mock data. Only the forum functionality is required for this task. The app must also be dockerized and deployed. Finally, since we only have a small time window for the presentation, it must be planned and practiced in advance to extract as much information as possible from the customers and to leave the best impression.

## Tasks

- [x] Implement the required functionality in the front-end
- [x] Dockerize and deploy the front-end application
- [x] Create documentation explaining the dockerization and deployment step-by-step
- [x] Plan and practice the presentation

## Estimated Time

**Estimated Time:**  15 hours

## Deadline

**Deadline:** 20/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @YavizGuldalf 
**Review Deadline:** 21/10/2024 - 23:59

**Comment by Elifnurdeniz** [comment]
We are done with all the implementations for the 1st milestone. The running instructions can be found at Readme.md file. We are ready for our presentation. Can you close the issue @YavizGuldalf?
