### ISSUE TITLE
1st Customer Presentation: Mobile Presentation

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#300]
## Issue Description
We decided that the mobile team will focus on showcasing the quizzes in the 1st customer presentation. In order to do this, the required pages have to be implemented and connected to the backend which will be serving mock data. Only the quiz functionality is required for this task. The app must also be packaged in to an `apk` file. Finally, since we only have a small time window for the presentation, it must be planned and practiced in advance to extract as much information as possible from the customers and to leave the best impression.

## Tasks

 - [ ] Implement the required functionality in the mobile app
 - [ ] Package the app (create an apk file)
 - [ ] Plan and practice the presentation

## Estimated Time

**Estimated Time:** 15 hours

## Deadline

**Deadline:** 20/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 21/10/2024 - 23:59
