### ISSUE TITLE
1st Customer Presentation: Backend Endpoint Implementation

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#302]
## Issue Description
We decided that the backend team will not be showing anything in particular for the 1st customer presentation but will instead be serving mock data over some endpoints for the presentation prepared by the mobile and front-end team. In order to do this, there must be endpoints serving mock data for both quiz and forum functionality. For the mobile presentation, word suggestions while creating a quiz should be fetchable from an endpoint, as well as a list of quizzes for the quiz feed. For the front-end presentation,  there should be an endpoint for returning a list of forum posts for the forum feed and an endpoint for returning the comments under a post. Finally, the back-end app must be dockerized and deployed. 

## Tasks

- [x] Discuss with the mobile team the endpoints they'll need for their presentation.
- [x] Create the endpoints needed by the mobile team.
- [x] Discuss with the front-end team the endpoints they'll need for their presentation.
- [x] Create the endpoints needed by the front-end team.
- [x] Dockerize and deploy the back-end app.

## Estimated Time

**Estimated Time:** 15 hours

## Deadline

**Deadline:** 20/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir 
**Review Deadline:** 21/10/2024 - 23:59

**Comment by oktayozel** [comment]
http://161.35.208.249:5173/

http://161.35.208.249:8000/

@Elifnurdeniz  can you close the issue after reviewing

**Comment by Elifnurdeniz** [comment]
Thanks.
