### ISSUE TITLE
Finalise Post Component Design

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#319]
## Issue Description

Finalise post design to be used in many other pages.

## Tasks

- [x] Add read less functionality for too large texts.
- [x] Make icons interactive.
- [x] Create mock data.
- [x] Adjust skeleton accordingly.
- [ ] #338

## Estimated Time

**Estimated Time:** 1.5 hours

## Deadline

**Deadline:** 19/10/2024 - 16:00

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 19/10/2024 - 17:00

**Comment by alitariksahin** [comment]
@Elifnurdeniz Making whole card clickable was not a good idea
