### ISSUE TITLE
Comment Component Design

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#321]
## Issue Description
The comment card should be designed and be added to post details page.

## Tasks

- [x] Design comment component
- [ ] Create mock data
- [ ] Make comment clickable.
- [x] Add a skeleton for it to be shown when loading.
- [x] Start designing post details page.

## Estimated Time

**Estimated Time:** 6 hours

## Deadline

**Deadline:** 20/10/2024 - 12:00

## Reviewer Assignment

**Reviewer:** @alitariksahin @yunusemreozdemir 
**Review Deadline:** 20/10/2024 - 18:00

**Comment by Elifnurdeniz** [comment]
I created the initial design of the comment component, its skeleton and the post details page [here](https://github.com/bounswe/bounswe2024group6/pull/337).

**Comment by Elifnurdeniz** [comment]
We later decided to remove the comment component and use the post component for commenting functionality too. So, this issue is redundant at the moment.
