### ISSUE TITLE
[Mobile]: Quiz Question Page

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#333]
## Issue Description
For the users to display the question and the answers, we need to implement a page with a design similar to below:

![image](https://github.com/user-attachments/assets/980f4320-a299-4d25-926f-8965c0b95039)

## Tasks

- [ ] Add navbar to the page 
- [ ] Add question box
- [ ] Add answer boxes
- [ ] Add next/ previous buttons

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 20/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @YavizGuldalf 
**Review Deadline:** 22/10/2024 - 23:59

**Comment by YavizGuldalf** [comment]
This is completed in #365 and will be further refined in #375.
