### ISSUE TITLE
[Mobile]: Quiz Details Page

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#334]
## Issue Description
For the users to display the metadata about a quiz, create a simple page.

![image](https://github.com/user-attachments/assets/649a3bfc-7f6c-473d-bd05-5f2157c580ab)

## Tasks

- [x] Add navbar to the page 
- [ ] Add detail box
- [x] Add take quiz and go back buttons

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 20/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @aoengin  
**Review Deadline:** 22/10/2024 - 23:59
