### ISSUE TITLE
Mobile: Create/Improve Icons

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#353]
## Issue Description
We need to create icons in ideally png or svg format for the mobile part of the project. Currently, we have some placeholders but there are problems with them. We also have some unused assets that should be cleaned from the repo. You can find a tentative list of icons I have identified for our use cases in the tasks section below. All of these can be found online relatively easily, but we must take care to ensure that they are in the proper format (png or svg). Also, I feel like it'd be best to have these images have the same canvas size if png format is used to keep things consistent

## Tasks

- [ ] Create/refine the profile picture icon.
- [ ] Create a full bookmark icon (shown when the item is bookmarked)
- [ ] Create an empty bookmark icon (shown when the item is not bookmarked)
- [ ] Create an empty like icon (shown when the item is not liked)
- [ ] Create a full  like icon (shown when the item is liked)
- [ ] Create a plus icon (used to show an option to add something)
- [ ] Create a minus icon (used to show an option to remove/delete something) (can optionally be replaced with a garbage can icon)
- [ ] Create the icons related to markdown editing, like the ones in the image below.
<img width="488" alt="Screenshot 2024-10-20 at 14 10 54" src="https://github.com/user-attachments/assets/ca3bbc81-a370-4021-a468-38952b928c1a">

## Estimated Time

**Estimated Time:** 45 mins

## Deadline

**Deadline:** 20/10/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @anilanlar 
**Review Deadline:** 21/10/2023 - 23:59
