### ISSUE TITLE
Frontend: Dockerize Frontend and Connect to Backend

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#368]
## Issue Description
It is time to dockerize the Frontend Application

## Tasks
- [x] A Dockerfile should be created for Frontend
- [x] Frontend should be integrated to the docker compose
- [x] Connection with the backend should be tested via an API route
- [x] Any issue in backend or frontend that fails docker compose up must be solved

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 21/10/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 22/10/2024 - 23:59

**Comment by yunusemreozdemir** [comment]
This is done in #371 can you check @Elifnurdeniz ?
