### ISSUE TITLE
[Mobile]: Quiz Creation Flow - QuizCreationSettings and QuizCreationInfo Pages   

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#375]
## Issue Description

UI components are implemented in QuizCreationSettings and QuizCreationInfo pages, however, the following changes should be done as the first milestone tasks. Some of the changes include editing the alignment of the UI components and their functionalities. Navigation operations are going to be handled in another issue. 

## Tasks
1- QuizCreationSettings:

- [x] The page needs to have a little margin on the top, otherwise the Navbar is too close to the top.

2- QuizCreationInfo:
- [x] The page needs to have a little margin on the top, otherwise the Navbar is too close to the top.
- [x] The question prompt should be editable. (It's statically set to 'Pasta' in this implementation.)
- [x] The question prompt should ideally have its own yellow container for a better visual.
- [x] The 'Add Question' button should only be pressable if all the answer and the question is filled.
- [x] This page needs a way of indicating what the right answer to the question is. This could be by changing the background/border color of one of the answer choices, or it could be done with the help of a small button on the top right of each answer choice.

## Deadline

**Deadline:**  22/10/2024- 08:00

## Reviewer Assignment

**Reviewer:** @YavizGuldalf 
**Review Deadline:**  22/10/2024- 08:00

**Comment by aoengin** [comment]
I've completed all requested features. Please see the related [PR](https://github.com/bounswe/bounswe2024group6/pull/403).

**Comment by YavizGuldalf** [comment]
Looks good to me, I have merged your PR.
