### ISSUE TITLE
[Mobile]: Quiz Creation Flow - Navigation Across Quiz Creation Flow Pages

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#377]
## Issue Description

UI components are implemented in QuizCreationSettings and QuizCreationInfo pages, however, the following changes should be done as the first milestone tasks. Some of the changes include editing the alignment of the UI components and their functionalities. Navigation operations are going to be handled in another issue. 

## Tasks
1- QuizCreationSettings:

- [ ]  The add questions button should route to an empty quizCreationQuestionList

2- QuizCreationInfo:
- [ ] The question type must come preselected OR the suggestions should only be presented after a question type is selected.
- [ ] The 'Add Question' button should add the question to the quiz list and navigate to the quizCreationQuestionList.
- [ ] The 'Go Back' button should navigate to the quizCreationQuestionList without adding the question.

1- QuizCreationQuestionList:

- [ ] The '+' icon next to the quiz name should navigate to QuizCreationInfo instead of just adding an item to the list.
- [ ] The recycle icon should reopen the question for modification.
- [ ] The Cancel button should navigate back to the QuizFeed.
- [ ] The Create Quiz button should navigate back to the QuizFeed. (we could also add a quick message showing that the question has been successfully created) (this button will eventually have to send data to backend as well)

## Deadline

**Deadline:**  22/10/2024- 08:00

## Reviewer Assignment

**Reviewer:** @anilanlar  
**Review Deadline:**  22/10/2024- 08:00

**Comment by aoengin** [comment]
All requirements are completed. @anilanlar
