### ISSUE TITLE
Mobile: Refactor and Connect Components for Prerelease

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#421]
## Issue Description
We need to look over how the app looks before the demo and prerelease and smooth out all of the easily fixable bugs we see. This involves connecting the related pages and going over our presentation plan and making sure each button works as intended.

## Tasks

- [ ] Remove headers from the pages that still have them
- [ ] For all the pages that will be used in the demo, add an onPress function if they don't have one yet.
- [ ] Go over the pages in the presentation plan

## Estimated Time

**Estimated Time:** 30 minutes

## Deadline

**Deadline:** 22/10/2024 - 08:00

## Reviewer Assignment

**Reviewer:** @Reviewer
**Review Deadline:** 22/10/2024 - 23:59
