### ISSUE TITLE
Creating List and Status of Deliverables And Addressed Requirements

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#433]
## Issue Description

The two tasks below should be filled for milestone report 1:

## Tasks

- [x] Creating List and Status of Deliverables
- [x] Listing Meeting and Reports
- [x] Listing Addressed Requirements
## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 25/10/2024 - 17:00

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 25/10/2024 - 17:00

**Comment by Elifnurdeniz** [comment]
I'm done with them can you check @arastasci ?

**Comment by arastasci** [comment]
Lgtm
