### ISSUE TITLE
Mobile: UI Redesign

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#434]
## Issue Description
After the customer milestone, we learned that the frontend team's design was prepared. Therefore, the mobile team will have to change the UI of the app to be more fitting to the frontend design. This is a big issue that will most likely require multiple PRs.

## Tasks
 - [ ] Change the UI design of the Navbar component
 - [ ] Change the UI design of the Home page
 - [ ] Change the UI design of the QuizCreationInfo page
 - [ ] Change the UI design of the QuizCreationQuestionList page
 - [ ] Change the UI design of the QuizCreationSettings page
 - [ ] Change the UI design of the QuizDetails page
 - [ ] Change the UI design of the QuizFeed page
 - [ ] Change the UI design of the QuizQuestion page
 - [ ] Change the UI design of the QuizResults page
 - [ ] Change the UI design of the register page

## Estimated Time
**Estimated Time:** 8 hours

## Deadline
**Deadline:** 03/11/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @YavizGuldalf  
**Review Deadline: ** 05/11/2024 - 23:59

**Comment by aoengin** [comment]
Everyone will be editing their part of the mobile pages. Therefore, we'll create separate issues for each part.
