### ISSUE TITLE
Backend: Search Functionality Endpoint

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#437]
## Issue Description
 We need to implement a browsing endpoint that will return related posts and quizzes. 

## Tasks

- [x] Integrate Lexvo API(Pending)
- [x] Implement endpoint logic to filter and return related posts and quizzes.(Pending)
- [x]  Retrieve Translation , Meanings and Related Words
- [ ] Test the endpoint for accuracy in returning relevant content.(Pending)
- [ ] Document the endpoint and usage instructions.(Pending)

## Estimated Time

**Estimated Time:** 8 hours
## Deadline

**Deadline:** 31/10/2024 - 17:00

## Reviewer Assignment

**Reviewer:** @YavizGuldalf @yunusemreozdemir 
**Review Deadline:**  1/11/2024 - 17:00

**Comment by YavizGuldalf** [comment]
Thank you Kaan, the meaning and translation fetch seems to work well.
