### ISSUE TITLE
Mobile: Redesign the Quiz Pages 

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#452]
## Issue Description
As the mobile team, we've decided to change the design based on the feedback we've collected during our first customer presentation to align with the front-end design. We need to edit the quiz pages to have a similar design to the front end.

## Tasks
- [x] Redesign quiz feed page 
- [x] Redesign quiz details page
- [x] Redesign quiz result page
- [x] Redesign quiz creation pages
- [x] Redesign quiz question pages 

## Estimated Time
**Estimated Time:** 4 hours 

## Deadline
**Deadline:** 01/11/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @anilanlar 

**Review Deadline:** 02/11/2024 - 23:59

**Comment by aoengin** [comment]
@anilanlar Please see the related [PR](https://github.com/bounswe/bounswe2024group6/pull/456).
