### ISSUE TITLE
Backend: Populate Database with Words, Translations and Categories

### ISSUE THREAD

**Issue by kaanyolcu22** [bounswe/bounswe2024group6#458]
## Issue Description
 We need to create the tables for words, translations and categories. In order to do so, first we need to find a proper dataset. For each word in the dataset we need to fetch necessary info from lexvo . Save the necessary files as csv. And then create the tables

## Tasks

- [x] ~Find Cefr level dataset~ (Completed)
- [ ] Fetch Lexvo data for every word (Pending)
- [ ] Write the necessary tables to the csv (Pending)

## Estimated Time

**Estimated Time:** 10 hours

## Deadline

**Deadline:** 5/11/2024-11:00

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 5/11/2024-15:00
