### ISSUE TITLE
[Mobile]: Implement "Other Profile" Page

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#466]
## Issue Description
Other profile pages need to implemented as per the new color palette and design. The pictures below is only for functionality purposes, it does not represent our updated UI.

<img width="228" alt="image" src="https://github.com/user-attachments/assets/f183fc47-7a37-43df-b872-7c1a0d918ad8"> 

## Tasks

- [ ] Implement the other profile - main page.
- [ ] Implement the other profile - followers page.
- [ ] Implement the other profile - following page.
- [ ] Implement the other profile - bookmarked quizzes page.
- [ ] Implement the other profile - profile posts page.
- [ ] Implement the other profile - liked posts page.
- [ ] Implement the other profile - comments page.

## Estimated Time

**Estimated Time:** 6 hours

## Deadline

**Deadline:** 8/11/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @aoengin  
**Review Deadline:** 10/11/2024 - 23:59
