### ISSUE TITLE
[Mobile]: Implementation of Forum Pages

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#468]
## Issue Description
Forum feed, post, post creation pages need to implemented. The pictures below is only for functionality purposes, it does not represent our updated UI.

<img width="374" alt="image" src="https://github.com/user-attachments/assets/6afefb63-1340-4708-85c6-46eb1adc9da4">

## Tasks

- [ ] Implement the forum feed page.
- [ ] Implement the forum post page.
- [ ] Implement the forum post creation page.

## Estimated Time

**Estimated Time:** 4 hours

## Deadline

**Deadline:** 8/11/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @YavizGuldalf   
**Review Deadline:** 10/11/2024 - 23:59
