### ISSUE TITLE
Mobile: Connect Mobile Pages to the Backend

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#487]
## Issue Description
We need to connect the mobile pages to the backend to make the quiz pages fully functional.

## Tasks
- [ ] Connect quiz creation pages to the backend.
- [ ] Connect quiz engagement pages to the backend.
- [ ] Connect quiz feed to the backend.

## Estimated Time
**Estimated Time:** 5 hours

## Deadline
**Deadline:** 18/11/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @anilanlar 
**Review Deadline:** 19/11/2024 - 23:59
