### ISSUE TITLE
Mobile: Enable Dark Mode on All Quiz Pages

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#505]
## Issue Description
We need to update all quiz pages to enable dark mode. This will align with the front-end and improve UX.

## Tasks
- [x] Enable dark mode on QuizFeed.
- [x] Enable dark mode on QuizCreationInfo.
- [x] Enable dark mode on QuizCreationQuestionList.
- [x] Enable dark mode on QuizCreationSettings.
- [x] Enable dark mode on QuizDetails.
- [x] Enable dark mode on QuizQuestion.
- [x] Enable dark mode on QuizResults.

## Estimated Time
**Estimated Time:** 4 hours

## Deadline
**Deadline:** 20/11/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @YavizGuldalf 
**Review Deadline:** 21/11/2024 - 23:59

**Comment by aoengin** [comment]
Please see the [related PR](https://github.com/bounswe/bounswe2024group6/pull/506).
