### ISSUE TITLE
Mobile: Login Token Management

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#531]
## Issue Description
We need to manage the access and refresh tokens returned by the backend on login requests.

## Tasks

- [x] Handle the storage and usage of the refresh token
- [x] Handle the storage and usage of the access token
- [x] Handle the storage and usage of user information (like username, name, etc. whatever is needed)

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 21/11/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @anilanlar 
**Review Deadline:** 24/10/2024 - 23:59
