### ISSUE TITLE
Forum Sorting Issue

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#547]
## Issue Description

Forum posts are displayed in a random order. Fix it and give a default sorting method.

## Tasks

- [x] Implement sorting features in forum
- [x] Give a default sorting
- [x] Implement sorting features in profile

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 23/11/2024 - 22:00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 24/11/2024 - 12:00
