### ISSUE TITLE
Make Notifications Functional

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#561]
## Issue Description

Using Activity Streams 2.0 protocol we've managed to create a notifications display, now it needs to be made interactive and functional, beautifying the view as well
## Tasks

- [x] Grab real time notifications from backend
- [x] beautify the notifications display e.g. adding header
- [x] make notifications interactive, (users need to be able to visit the profile pages of others)
- [ ] (optional) implement follow back functionality

## Estimated Time

**Estimated Time:** 4 hours

## Deadline

**Deadline:** 24/11/2024 - 20.00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 24/11/2024 - 20.00
