### ISSUE TITLE
Mobile: Resolve the Bug on the Quiz Creation Info Page

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#565]
## Issue Description
Problem: The application throws a warning: "Each child in a list should have a unique 'key' prop." This issue arises during the rendering of the QuizCreationInfo component, indicating that one or more child elements in the list do not have a properly assigned key prop.

Impact: The warning may cause inefficient updates and debugging difficulties. While it does not break functionality, it violates best practices and can lead to unexpected behavior

<img width="822" alt="Screenshot 2024-11-23 at 12 14 26" src="https://github.com/user-attachments/assets/102230f7-4e7a-4624-9231-5e135d634059">

## Tasks

- [x]  Assign a unique key to each child element.
- [x] Verify the warning is resolved in the console.
- [x] Test the page for any unexpected behavior.

## Estimated Time
**Estimated Time:** 20 minutes

## Deadline
**Deadline:** 23/11/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @anilanlar 
**Review Deadline:** 24/11/2024 - 23:59

**Comment by aoengin** [comment]
Tests are manually conducted and works well. Please see the [related PR](https://github.com/bounswe/bounswe2024group6/pull/566). @anilanlar
