### ISSUE TITLE
Mobile: Remove Navigation Bar from Login and Register Pages

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#569]
## Issue Description
The navigation bar should be removed from the Login and Register pages on mobile devices to improve user focus and simplify the interface. 

## Tasks
- [x] Update the navigation component to hide the bar on specified pages
- [x] Test the changes on Login, Register pages across different mobile devices
- [x] Review changes and ensure no unintended UI/UX regressions on other pages

## Estimated Time
**Estimated Time:** 45 mins

## Deadline
**Deadline:** 23/11/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @YavizGuldalf 
**Review Deadline:** 24/11/2024 - 23:59

**Comment by aoengin** [comment]
Please see the [related PR.](https://github.com/bounswe/bounswe2024group6/pull/575)
