### ISSUE TITLE
Frontend: Create Testing Environment

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#572]
## Issue Description
We need to create a testing environment with necessary tools set up so that we can start writing unit tests.

## Tasks
- [x] Set up Vitest
- [x] Set up Mock Service Worker
- [x] Set up `@testing-library/react`
- [x] Write an example unit test

## Estimated Time
**Estimated Time:** 3 hours

## Deadline
**Deadline:** 23/11/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 24/11/2024 - 23:59

**Comment by yunusemreozdemir** [comment]
This is done in #576, can you check @Elifnurdeniz?
