### ISSUE TITLE
Mobile: Connect Profile to Backend

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#603]
## Issue Description
We want to connect the profile pages to the backend. This issue does not cover the connection of the various cards that are used in the profile tab, EXCEPT the userCard component.

## Tasks

- [ ] Fetch profile info when the user first opens the profile tab
- [ ] Fetch the created quizzes of the user 
- [ ] Fetch the solved quizzes of the user
- [ ] Fetch the comments/posts of the user
- [ ] Fetch the bookmarked/liked quizzes of the user
- [ ] Fetch the bookmarked/liked posts/comment of the user
- [ ] Send an update request when profile is edited.
- [ ] Send a follow/unfollow request when the related button is pressed in the userCard
- [ ] Fetch other user profile info when you navigate to another users profile
- [ ] Fetch the created quizzes of other user 
- [ ] Fetch the solved quizzes of other user
- [ ] Fetch the comments/posts of other user

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 24/11/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @anilanlar 
**Review Deadline:** 25/11/2024 - 21:00
