### ISSUE TITLE
Small Changes To Profile And Quizzes

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#647]
## Issue Description

Selim Bey's final touches

## Tasks

- [x] Make posts first section
- [x] Add default bio
- [x] Remove explanations in empty tabs
- [x] Give better default pictures to quizzes

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 25/11/2024 - 16:00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 25/11/2024 - 16:00

**Comment by Elifnurdeniz** [comment]
[HERE](https://github.com/bounswe/bounswe2024group6/pull/653) @alitariksahin
