### ISSUE TITLE
Mobile: Refresh Profile Page Whenever Something Changes

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#648]
## Issue Description
We want the (own) profile page to refetch the userInfo whenever something about the fields displayed changes.

## Tasks

- [ ] Refresh the profile page whenever the createdQuizzes change.
- [ ] Refresh the profile page whenever the solvedQuizzes change.
- [ ] Refresh the profile page whenever the followers change
- [ ] Refresh the profile page whenever the following changes
- [ ] Refresh the profile page whenever the level/bio changes via edit profile

Alternatively, we could also make it so that the profile page info is refetched every time it comes into view.

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 25/10/2024 - 02:00

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:** 25/10/2024 - 21:00

**Comment by YavizGuldalf** [comment]
You can see the related PR [here](https://github.com/bounswe/bounswe2024group6/pull/655), @aoengin.
