### ISSUE TITLE
Mobile: Unit Test for Testing Quiz Review

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#682]
## Issue Description
Implement and validate unit tests to ensure the functionality of the quiz review feature.

## Tasks
- [x] Write unit tests for quiz review.
- [x] Test error handling.
- [x] Validate expected outputs against requirements.

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 25/11/2024 - 20:00

## Reviewer Assignment
**Reviewer:** @YavizGuldalf 
**Review Deadline:** 25/11/2024 - 22:00
