### ISSUE TITLE
[Mobile]: Redesign Forum Pages

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#708]
## Issue Description
As the mobile team, we've decided to change the design based on the feedback we've collected during our first customer presentation to align with the front-end design. We need to edit the forum pages to have a similar design to the front end.

## Tasks

- [x]  Redesign forum feed page
- [x] Redesign forum creation page
- [x] Redesign create forum page

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 28/11/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @YavizGuldalf  
**Review Deadline:** 29/11/2024 - 17:00

**Comment by YavizGuldalf** [comment]
This issue should have been automatically closed when the linked PR was merged, but since the PR was linked after it was merged this issue was left accidentally open. I am now closing it.
