### ISSUE TITLE
Mobile: Bookmark-able Words + Dictionary

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#710]
## Issue Description
In the second customer milestone, the possibility of a new feature was brought up. This feature involves allowing users to bookmark words and see them on their profile. Being able to see possible usages and meanings of the words could also be very helpful in this regard. We already have a few endpoints ready in the backend, they can be used to implement this feature.

## Tasks

- [ ] Use the pressable text component to create an in-app dictionary.
- [ ] Create a new ModalDictionary component that when rendered will show the meaning of the word in Turkish/English and some examples. This component must also contain a bookmark button.
- [ ] Create a new bookmarked words page that can be navigated from the user profile
## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 01/12/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @anilanlar
**Review Deadline:** 10/12/2024 - 23:59
