### ISSUE TITLE
Like Unlike Posts

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#713]
## Issue Description
Implement endpoints for liking and unliking posts.

## Tasks

- [ ] Like Post Endpoint
- [ ] Unlike Post Endpoint
- [ ] Urls.py
- [ ] update models accordingly.

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 20/11/2024 

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 20/11/2024

**Comment by oktayozel** [comment]
https://github.com/bounswe/bounswe2024group6/commit/7ffc9868a2568dc5aac65828f31072461d14def6
