### ISSUE TITLE
Activity Streams and Notifications Endpoints

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#715]
## Tasks

- [ ] Activity Streams Model
- [ ] Activity Streams for given user enndpoint
- [ ] Add activity streams to all existing endpoints.

## Estimated Time

**Estimated Time:** 5 hours

## Deadline

**Deadline:** 20/12/2024

## Reviewer Assignment

**Reviewer:** @arastasci 
**Review Deadline:** 20/12/2024

**Comment by oktayozel** [comment]
https://github.com/bounswe/bounswe2024group6/commit/2b21e7cd1cf713bf0aa27833d46ad57ac4677925
https://github.com/bounswe/bounswe2024group6/commit/f4113b1a361249615936ec3860967cb4d4a5ec12

**Comment by oktayozel** [comment]
https://github.com/bounswe/bounswe2024group6/commit/a25e2ab04a4749829ffa4a9ae9b278159196fd18

**Comment by oktayozel** [comment]
https://github.com/bounswe/bounswe2024group6/commit/d11bc276b6a844b79d1f9ea2c1070b1bb61c7d68

**Comment by arastasci** [comment]
thanks, @oktayozel!
