### ISSUE TITLE
Mobile: Type Information on Quiz Question Creation 

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#720]
## Issue Description
Feedback from the second customer milestone highlighted the need to make question types clearer to enhance usability and comprehension. To address this, we need to integrate type information into the quiz creation process.

## Tasks
- [x] Find and add "information" icon. 
- [x] Implement the logic to display type information in a modal when the user clicks the info button.
- [x] Test the modal functionality to ensure it displays correct type information and closes properly.

## Estimated Time
**Estimated Time:** 1 hour

## Deadline
**Deadline:** 6/12/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @YavizGuldalf 
**Review Deadline:** 7/12/2024 - 23:59

**Comment by aoengin** [comment]
@YavizGuldalf Please see the [Related PR](https://github.com/bounswe/bounswe2024group6/pull/721).
