### ISSUE TITLE
Post Endpoints

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#723]
## Issue Description
Implement CRUD endpoints for posts.

## Tasks
- [ ] Create post endpoint
- [ ] Delete post endpoint
- [ ] Get posts of user (3-3-3 endpoint)
- [ ] Get feed endpoint
- [ ] Update post model as needed

## Estimated Time
**Estimated Time:** 5 hours

## Deadline
**Deadline:** 20/11/2024

## Reviewer Assignment
**Reviewer:** @arastasci
**Review Deadline:** 20/11/2024
