### ISSUE TITLE
Update Models

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#724]
## Issue Description
Update the models to include additional fields as needed.

## Tasks
- [ ] Add isLiked field
- [ ] Add isFollowed field
- [ ] serialize comments in posts
- [ ] bookmarks addition to post model
- [ ] profile model refactoring

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 20/11/2024

## Reviewer Assignment
**Reviewer:** @arastasci
**Review Deadline:** 20/11/2024
