### ISSUE TITLE
Follow - Unfollow Endpoints

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#725]
## Issue Description
Implement endpoints related to the follow/unfollow functionality.

## Tasks
- [ ] Follow user endpoint
- [ ] Unfollow user endpoint
- [ ] Get followers endpoint
- [ ] Get following endpoint

## Estimated Time
**Estimated Time:** 4 hours

## Deadline
**Deadline:** 20/11/2024

## Reviewer Assignment
**Reviewer:** @arastasci
**Review Deadline:** 20/11/2024

**Comment by arastasci** [comment]
thanks, @oktayozel!
