### ISSUE TITLE
Testing Profile Endpoints

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#727]
## Issue Description
Write Django tests for profile views.

## Tasks
- [ ] Write Django tests for deleting profile
- [ ] Write Django tests for creating profile
- [ ] Write Django tests for getting profile

## Estimated Time
**Estimated Time:** 3 hours

## Deadline
**Deadline:** 20/11/2024

## Reviewer Assignment
**Reviewer:** @arastasci
**Review Deadline:** 20/11/2024
