### ISSUE TITLE
Write tests for authentication

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#728]
## Issue Description
Write Django tests for authentication endpoints.

## Tasks
- [ ] Write Django tests for signup
- [ ] Write Django tests for signin
- [ ] Write Django tests for logout

## Estimated Time
**Estimated Time:** 3 hours

## Deadline
**Deadline:** 20/11/2024

## Reviewer Assignment
**Reviewer:** @arastasci
**Review Deadline:** 20/11/2024

**Comment by arastasci** [comment]
LGTM.
