### ISSUE TITLE
Bookmark Endpoints

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#731]
## Issue Description
Implement bookmark functionality and model.

## Tasks
- [ ] Write bookmark model
- [ ] Write bookmark endpoint
- [ ] Write unbookmark endpoint
- [ ] Get bookmarked posts endpoint

## Estimated Time
**Estimated Time:** 3 hours

## Deadline
**Deadline:** 20/11/2024

## Reviewer Assignment
**Reviewer:** @arastasci
**Review Deadline:** 20/11/2024
