### ISSUE TITLE
Comment Endpoints

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#733]
## Issue Description
Implement comment functionality and endpoints.

## Tasks
- [ ] Write comment model
- [ ] Write recursive comments
- [ ] Write comment endpoint
- [ ] Write delete comment endpoint

## Estimated Time
**Estimated Time:** 4 hours

## Deadline
**Deadline:** 20/11/2024

## Reviewer Assignment
**Reviewer:** @arastasci
**Review Deadline:** 20/11/2024

**Comment by oktayozel** [comment]
https://github.com/bounswe/bounswe2024group6/commit/856f7c6ac92ae0ee1fc78e716fd15f166e74e7e1
https://github.com/bounswe/bounswe2024group6/commit/8272987211a1c05b58ab56a2f7d256efbe115914
