### ISSUE TITLE
Like/Unlike Endpoints

### ISSUE THREAD

**Issue by oktayozel** [bounswe/bounswe2024group6#734]
## Issue Description
Implement endpoints for liking and unliking posts.

## Tasks
- [ ] Like Post Endpoint
- [ ] Unlike Post Endpoint
- [ ]Update  Urls.py
- [ ] Update models accordingly

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 20/11/2024

## Reviewer Assignment
**Reviewer:** @arastasci
**Review Deadline:** 20/11/2024

**Comment by arastasci** [comment]
LGTM.
