### ISSUE TITLE
Mobile: Add Admin Options

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#737]
## Issue Description
We want to create an admin options component that will show up when a logged-in admin user presses and holds on the following components: 

* UserCard
* QuizCard
* PostCard
* CommentCard

## Tasks

- [x] Create an AdminOptions component
- [x] Add AdminOptions to UserCard
- [x] Add AdminOptions to QuizCard
- [x] Add AdminOptions to PostCard
- [x] Add AdminOptions to CommentCard
- [ ] Connect AdminOptions to the backend

## Estimated Time

**Estimated Time:** 4 hours

## Deadline

**Deadline:** 15/12/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:** 16/12/2024 - 21:00
