### ISSUE TITLE
Frontend: Connect Quiz Related Pages To Backend

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#739]
## Issue Description

Designed quiz pages need to be connected to backend.

## Tasks

- [x] Connect Quiz Forum Page
- [x] Connect Quiz Details Page
- [x] Connect Quiz Solve Page
- [x] Connect Quiz Results Page

## Estimated Time

**Estimated Time:** 8 hours

## Deadline

**Deadline:** 14/12/2024 - 23:00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 14/12/2024 - 23:59

**Comment by Elifnurdeniz** [comment]
Connections are done for now. There are a few more implementations needed such as quiz recommendation, etc. They will be handled after frontend meeting. Can you check @alitariksahin ?
