### ISSUE TITLE
Mobile[LAB]: User Tests For Mobile

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#752]
## Issue Description
Develop a comprehensive suite of user tests for the mobile application to ensure all features and functionalities perform as expected. The tests should cover various user scenarios, edge cases, and device compatibility.

## Tasks
- [x] Create user tests for login and registration.
- [x] Create user tests for forum.
- [x] Create user tests for quizzes.
- [x] Create user tests for profile.

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 14/12/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @YavizGuldalf 
**Review Deadline:** 15/12/2024 - 23:59

**Comment by aoengin** [comment]
Please see the tests on the [related wiki page](https://github.com/bounswe/bounswe2024group6/wiki/User-Tests-for-Mobile). @YavizGuldalf

**Comment by YavizGuldalf** [comment]
The tests look good, but there are a few adjustments I'll suggest. First of all, we can change the name of the Tests 5, 6 and 7. They are all named 'Quiz' right now, but I feel 'Quiz Like/Unlike', 'Quiz Solving', and 'Quiz Review' are more appropriate names for those tests. Also, I noticed some inconsistencies in some tests. 

<img width="905" alt="Screenshot 2024-12-10 at 19 26 54" src="https://github.com/user-attachments/assets/53313d0f-05a4-4207-989f-7baf1a56e6a5">

The steps 4 and 5 should be switched in Test 5, as the like count goes **down** after unliking. You can also add another step at the end to check if the like count has gone down and the star has gone white.

<img width="909" alt="Screenshot 2024-12-10 at 19 27 32" src="https://github.com/user-attachments/assets/e00680a6-d28d-4ada-bc52-3f491ee1eaa7">

Step 7 and Step 6 should change places in Test 6. Question progress increases after each question is answered, not when the finish button is pressed.
