### ISSUE TITLE
Lab: User Tests for Frontend

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#754]
## Issue Description
Develop a comprehensive suite of user tests for the frontend application to ensure all features and functionalities perform as expected. The tests should cover various user scenarios and edge cases.

## Tasks
- [x] Create user tests for login and registration.
- [x] Create user tests for forum.
- [x] Create user tests for quizzes.
- [x] Create user tests for profile.

## Estimated Time
**Estimated Time:** 2 hours

## Deadline
**Deadline:** 10/12/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @YavizGuldalf 
**Review Deadline:** 11/12/2024 - 23:59

**Comment by yunusemreozdemir** [comment]
This is done in [Frontend User Tests](https://github.com/bounswe/bounswe2024group6/wiki/Frontend-User-Tests), can you check @YavizGuldalf ?
