### ISSUE TITLE
Mobile: Connect Bookmarked Words with Backend

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#773]
## Issue Description
We want to be able to connect the bookmark button in the mobile dictionary with the backend so that users can actually bookmark/unbookmark some words. We also want to fetch the bookmarked words in the profile.

## Tasks

- [ ] Connect bookmarking functionality
- [ ] Connect removing bookmark functionality
- [ ] Fetch the bookmarked words from the backend in the related profile page

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 13/12/2024 - 05:00

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:** 16/12/2024 - 23:59
