### ISSUE TITLE
[Mobile]: Add PressableText Component to the Quiz Screens

### ISSUE THREAD

**Issue by anilanlar** [bounswe/bounswe2024group6#780]
## Issue Description

Add PressableText Component to the Quiz Screens. 

## Tasks

- [x] Quiz Details page
- [x] Quiz Question page
- [x] Quiz Results page
- [x] Quiz Review page
- [x] Quiz Card Component

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 12/12/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @YavizGuldalf 
**Review Deadline:** 12/12/2024 - 23:59

**Comment by anilanlar** [comment]
You can find the related [PR](https://github.com/bounswe/bounswe2024group6/pull/781/commits)
