### ISSUE TITLE
Frontend: Complete Guest View

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#803]
## Issue Description
Guest View should be completed by rejecting unauthorized actions and displaying a login/register modal.

## Tasks
- [x] Implement Login/Register Modal
- [x] Restrict Forum actions
- [x] Restrict Quiz actions
- [x] Restrict Profile actions

## Estimated Time
**Estimated Time:** 5 hours

## Deadline
**Deadline:** 15/12/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 16/12/2024 - 23:59

**Comment by yunusemreozdemir** [comment]
This is done in #805 , can you check @Elifnurdeniz ?
