### ISSUE TITLE
Implement Recursive Post-Comment Pages

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#804]
## Issue Description

Post pages are ready but comment pages are not. They need to be implemented before the last milestone.

## Tasks

- [x] Create comments' own pages
- [x] Check if all features work correctly
- [x] Added bookmark feature to comments

## Estimated Time

**Estimated Time:** 4 hours

## Deadline

**Deadline:** 15/12/2024 - 16:00

## Reviewer Assignment

**Reviewer:** @yunusemreozdemir 
**Review Deadline:** 15/12/2024 - 17:00

**Comment by Elifnurdeniz** [comment]
It is finished in [here](https://github.com/bounswe/bounswe2024group6/pull/871) @yunusemreozdemir
