### ISSUE TITLE
Frontend: Implement Dictionary

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#806]
## Issue Description
Now that the word related endpoints are ready, we can implement the word press/dictionary functionality.

## Tasks
- [ ] Create the Dictionary Modal
- [ ] Make Forum related contents pressable
- [ ] Make Profile related contents pressable
- [ ] Make Dictionary contents pressable

## Estimated Time
**Estimated Time:** 4 hours

## Deadline
**Deadline:** 15/12/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 16/12/2024 - 23:59

**Comment by yunusemreozdemir** [comment]
This is done in #808 , can you check @Elifnurdeniz ?
