### ISSUE TITLE
Mobile: Connect the Edit Profile Picture with Backend & Update Design

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#807]
## Issue Description
The backend endpoint for uploading custom pictures for a user's profile picture is now ready. We need to connect the mobile design with this endpoint. While working on this, we should also change the edit profile page in the mobile to remove the "Name" field (as it is not used anywhere else, neither backend nor frontend), and also update the profile/other profile pages to display username in place of name.

## Tasks

- [ ] Connect the profile page image to the backend
- [ ] Remove the name field from the EditProfile page
- [ ] Replace the name field with the username field in the profile/other profile pages.

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 14/12/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:** 16/12/2024 - 20:00
