### ISSUE TITLE
Implement liked quizzes and posts

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#819]
## Issue Description

Add liked quizzes, comments and posts to profile.

## Tasks

- [x] Add liked quizzes
- [x] Add liked posts 
- [x] Add liked comments

## Estimated Time

**Estimated Time:** 3 hours

## Deadline

**Deadline:** 15/12/2024 - 22:00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 15/12/2024 - 23:00

**Comment by Elifnurdeniz** [comment]
I added liked quizzes here but liked posts endpoint is not ready at backend. [here](https://github.com/bounswe/bounswe2024group6/pull/843)

**Comment by Elifnurdeniz** [comment]
It is done in [here](https://github.com/bounswe/bounswe2024group6/pull/877/)
