### ISSUE TITLE
Mobile: Connect Quiz Like Feature to The Backend on Quiz Pages

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#828]
## Issue Description
Integrate the quiz like feature for the quiz feed and quiz result pages with the backend API to enable functionality for liking quizzes and syncing the like status.

## Tasks
- [x] Implement API integration on the quiz feed to send like data.
- [x] Implement API integration on the quiz result page to handle quiz-like functionality.
- [x] Test the quiz like feature thoroughly to ensure it works across different scenarios (e.g. multiple users).

## Estimated Time
**Estimated Time:** 90 mins

## Deadline
**Deadline:** 15/12/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @YavizGuldalf 
**Review Deadline:** 16/12/2024 - 20:00
