### ISSUE TITLE
Mobile: Guest View for Search, Profile and Home Tabs

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#848]
## Issue Description
We want to go over the requirements and adjust the pages so that the guests are able to perform the required actions in the app without having to log in. This issue is concerned with the Guest View for Search, Profile and Home tabs. The Quiz and Forum tabs will be handled separately. 

## Tasks

- [x] Enable guests to be able to search
- [x] Disable guests from pressing the follow/unfollow button and from pressing the UserCard to navigate to another user's profile
- [ ] Disable guests from pressing the like/bookmark button in quizCard, postCard and forumCard
- [x] Disable the guests from being able to navigate to the profile tab

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 15/12/2024 - 17:00

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:** 15/12/2024 - 20:00
