### ISSUE TITLE
Mobile: Connect Quiz Bookmark Feature to The Backend on Quiz Pages

### ISSUE THREAD

**Issue by aoengin** [bounswe/bounswe2024group6#859]
## Issue Description
Integrate the quiz bookmark feature for the quiz feed and quiz result pages with the backend API to enable functionality for bookmarking quizzes and syncing the bookmark status.

## Tasks
- [x] Implement API integration on the quiz feed to send bookmark data.
- [x] Implement API integration on the quiz result page to handle quiz-bookmark functionality.
- [x] Remove bookmark from quiz details page. 
- [x] Test the quiz bookmark feature thoroughly to ensure it works across different scenarios (e.g. multiple users).

## Estimated Time
**Estimated Time:** 90 mins

## Deadline
**Deadline:** 15/12/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @YavizGuldalf 
**Review Deadline:** 16/12/2024 - 19:05
