### ISSUE TITLE
Mobile: Bookmarked Quizzes Page and the Buttons in the QuizCard

### ISSUE THREAD

**Issue by YavizGuldalf** [bounswe/bounswe2024group6#876]
## Issue Description
In the profile tab, the bookmarked quizzes page does not currently work. It fetches the data but does not actually save it. Also, now that the related endpoints are ready, the buttons on the quiz card component should be made functional and send requests to the backend.

## Tasks

- [ ] Make Bookmarked Quizzes page work
- [ ] Make the like button work on the QuizCard
- [ ] Make the bookmark button work on the QuizCard

## Estimated Time

**Estimated Time:** 1 hour

## Deadline

**Deadline:** 15/12/2024 - 23:59

## Reviewer Assignment

**Reviewer:** @aoengin
**Review Deadline:** 16/12/2024 - 02:00
