### ISSUE TITLE
Frontend: Complete Activity Stream Notifications

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#901]
## Issue Description
We are now generating new activity streams that were not available in the previous milestone. We should update our notifications system in the frontend to accommodate these changes.

## Tasks
- [x] X solved your quiz.
- [x] X deleted your quiz.
- [x] X liked your quiz.
- [x] X liked your comment.
- [x] X deleted your comment.
- [x] X deleted your post.
- [x] X unfollowed you.

## Estimated Time
**Estimated Time:** 1 hours

## Deadline
**Deadline:** 16/12/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 17/12/2024 - 23:59

**Comment by yunusemreozdemir** [comment]
This is done in #911 , can you check @Elifnurdeniz ?
