### ISSUE TITLE
Frontend: Add Image Adding Functionality to Quiz Questions

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#915]
## Issue Description

Users should be able to either add pictures to their questions manually or generate pictures based on the word given.
## Tasks

- [x] Add manual picture adding functionality
- [x] Add picture generation functionality
- [x] Display added pictures in related pages

## Estimated Time

**Estimated Time:** 8 hours

## Deadline

**Deadline:** 16/12/2024 - 15:00

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz @yunusemreozdemir 
**Review Deadline:** 16/12/2024 - 20:00
