### ISSUE TITLE
Frontend: Write Guest and Admin View Unit Tests

### ISSUE THREAD

**Issue by yunusemreozdemir** [bounswe/bounswe2024group6#934]
## Issue Description
Now that the Guest and Admin Views are implemented in the frontend, we should write unit tests to test them.

## Tasks
- [x] Fix failing forum tests
- [x] Write Guest View forum tests
- [x] Write Admin View forum tests

## Estimated Time
**Estimated Time:** 1.5 hours

## Deadline
**Deadline:** 16/12/2024 - 23:59

## Reviewer Assignment
**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 17/12/2024 - 23:59

**Comment by yunusemreozdemir** [comment]
This is done in #939 , can you check @Elifnurdeniz ?
