### ISSUE TITLE
Frontend: Fix Quiz Related Skeletons

### ISSUE THREAD

**Issue by alitariksahin** [bounswe/bounswe2024group6#947]
## Issue Description

Quiz skeletons need to be arranged in harmony with the original components
## Tasks

- [x] Fix quiz view skeleton
- [x] Fix quiz question skeleton
- [x] Fix quiz end skeleton

## Estimated Time

**Estimated Time:** 2 hours

## Deadline

**Deadline:** 16/12/2024 - 20:00

## Reviewer Assignment

**Reviewer:** @Elifnurdeniz 
**Review Deadline:** 16/12/2024 - 23:00
