### ISSUE TITLE
Last Touches

### ISSUE THREAD

**Issue by Elifnurdeniz** [bounswe/bounswe2024group6#966]
## Issue Description

There are still some features to fix. Make a general review and correct them.

## Tasks

- [x] Review
- [x] Fix post comments for the 100th time
- [x] Fix non incrementing quiz likes in the details page
- [x] Fix long answers not fitting issue in quizzes
- [x] Fix like and bookmark in quiz results
- [x] Fix filtering-sorting disabling each other error

## Estimated Time

**Estimated Time:** 1.5 hours

## Deadline

**Deadline:** 16/12/2024 - 21:00

## Reviewer Assignment

**Reviewer:** @alitariksahin 
**Review Deadline:** 16/12/2024 - 21:00
